import Wrapper from '@/components/shared/Wraper'
import './globals.css'
import type { Metadata } from 'next'
import { Maven_Pro, } from 'next/font/google'

const inter = Maven_Pro({ subsets: ['latin'],
weight: ["400","500","700","900","600","800"] })

export const metadata: Metadata = {
  title: 'New project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">


      <body className={inter.className}>
        <Wrapper>
        {children}
        </Wrapper>
        </body>
    </html>
  )
}
