export {default as hero1GirlImage} from "./Images/HeroImages/header1.webp"
export {default as ftr1} from "./Images/HeroImages/Featured1.webp"
export {default as ftr2} from "./Images/HeroImages/Featured2.webp"
export {default as ftr3} from "./Images/HeroImages/Featured3.webp"
export {default as ftr4} from "./Images/HeroImages/Featured4.webp"